### ISSUE TITLE
Is this repository still alive?

### ISSUE THREAD

**Issue by peterzcc** [222464/PGE#10]

**Comment by 222464** [comment]
Hello,

Sorry about the lack of updates on this repository. The reason for this is that we are currently working on another large project. That project will likely need PGE for some of its demos, so you will probably see some updates to PGE soon.

**Comment by peterzcc** [comment]
Hi @222464 ,

Thanks for your reply! Good luck and I will wait and see if the PGE can work properly on my machine once there are more updates.
