### ISSUE TITLE
my install process log in ubuntu14

### ISSUE THREAD

**Issue by zdx3578** [222464/PGE#6]
speedup pip in china: http://theo.im/blog/2014/05/20/use-aliyun-mirror-to-boost-up-download-speed/
mkdir -p ~/.pip
touch ~/.pip/pip.conf
sed -i.backup -r \
    's/^index-url\s_=\s_.+$/index-url = http:\/\/mirrors.aliyun.com\/pypi\/simple\//' \
    ~/.pip/pip.conf
# If file not changed, write contents back to pip.conf

diff "~/.pip/pip.conf" "~/.pip/pip.conf.backup" &> /dev/null
if [ $? -eq 0 ]; then
cat > ~/.pip/pip.conf <<EOF
[global]
index-url = http://mirrors.aliyun.com/pypi/simple/
EOF
fi

[global]
index-url = http://mirrors.aliyun.com/pypi/simple/
[install]
trusted-host=mirrors.aliyun.com

---

sudo apt-get install build-essential checkinstall  git vim python-pip python-dev  zlib1g-dev libglu1-mesa-dev

first sudo  pip install numpy;then install gym

$ sudo apt-get install libpng-dev libjpeg-dev libxxf86vm1 libxxf86vm-dev libxi-dev libxrandr-dev
## $ sudo apt-get install mesa-common-dev

cmake: ref https://github.com/openai/gym/blob/box2dtests/.travis.yml#L20-L22  or
wget https://cmake.org/files/v3.4/cmake-3.4.3-Linux-x86_64.sh
./cmake-3.4.3-Linux-x86_64
cd cmake-3.4.3-Linux-x86_64

sudo apt-get install libopenal-dev

ref  http://gamedev.stackexchange.com/questions/111203/undefined-reference-to-std-throw-out-of-range-fmt
sudo add-apt-repository ppa:ubuntu-toolchain-r/test
sudo apt-get update
sudo apt-get install gcc-4.9 g++-4.9

wget http://www.sfml-dev.org/files/SFML-2.3.2-linux-gcc-64-bit.tar.gz
tar -zxvf  SFML-2.3.2-linux-gcc-64-bit.tar.gz

ref http://www.sfml-dev.org/tutorials/2.0/start-linux.php
 if SFML is not available as an official package. Download the SDK from the download page, unpack it and copy the files to your preferred location: either a separate path in your personal folder (like /home/me/sfml), or a standard path (like /usr/local).
cp to /usr/local/

or export   SFML_ROOT=/opt/practice/pge/SFML-2.3.2/

ref: http://www.sfml-dev.org/tutorials/2.3/window-opengl.php
OpenGL versions above 3.0 are supported by SFML (as long as your graphics driver can handle them). Support for selecting the profile of 3.2+ contexts and whether the context debug flag is set was added in SFML 2.3. The forward compatibility flag is not supported. By default, SFML creates 3.2+ contexts using the compatibility profile because the graphics module makes use of legacy OpenGL functionality. 

check opengl version:
glxinfo|grep version
my out:
zdx@zdx-535U3C:~$ glxinfo |grep version
server glx version string: 1.4
client glx version string: 1.4
GLX version: 1.4
OpenGL core profile version string: 4.1 (Core Profile) Mesa 11.3.0-devel (git-877a802 2016-05-18 trusty-oibaf-ppa)
OpenGL core profile shading language version string: 4.10
OpenGL version string: 3.0 Mesa 11.3.0-devel (git-877a802 2016-05-18 trusty-oibaf-ppa)
OpenGL shading language version string: 1.30
OpenGL ES profile version string: OpenGL ES 3.0 Mesa 11.3.0-devel (git-877a802 2016-05-18 trusty-oibaf-ppa)
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.00
zdx@zdx-535U3C:~$

update opengl ref: http://askubuntu.com/questions/501560/how-to-update-opengl-driver-on-ubuntu-14-04-lts

cd /opt/practice/pge/PGE/pge/
 /opt/practice/pge/cmake-3.5.2-Linux-x86_64/bin/cmake .  
make

and will ok!
now in this dir have pge file

---

if ubuntu black screen,cant login

:      sudo apt-get update
   sudo apt-get install xserver-xorg-lts-quantal
   sudo dpkg-reconfigure xserver-xorg-lts-quantal
   sudo reboot
ref :   http://www.2cto.com/os/201305/213737.html

**Comment by rcrowder** [comment]
@zdx3578 Thanks for these steps. I have always had trouble with using the gmake built steps with bullet3. The lib install wouldn't work, even with INSTALL_LIBS set. I did manage to use cmake with Bullet3, and have added that to the PGE Readme in this PR https://github.com/222464/PGE/pull/7
cc @222464 I think this issue can be closed now?

**Comment by zdx3578** [comment]
ubuntu 16 source install SFML
:  https://gitlab.peach-bun.com/pinion/SFML/commit/3383b4a472f0bd16a8161fb8760cd3e6333f1782.patch

From 3383b4a472f0bd16a8161fb8760cd3e6333f1782 Mon Sep 17 00:00:00 2001
From: David Yip yipdw@member.fsf.org
Date: Sun, 8 May 2016 20:24:35 -0500
Subject: [PATCH] A workaround for lingering GCC 5.3 errors.

See also:
- https://github.com/nothings/stb/issues/280

## \* https://bugs.launchpad.net/ubuntu/+source/gcc-5/+bug/1568899

 src/SFML/Graphics/CMakeLists.txt | 7 +++++++
 1 file changed, 7 insertions(+), 0 deletions(-)

diff --git a/src/SFML/Graphics/CMakeLists.txt b/src/SFML/Graphics/CMakeLists.txt
index 6f02fb6..bdc84e7 100644
--- a/src/SFML/Graphics/CMakeLists.txt
+++ b/src/SFML/Graphics/CMakeLists.txt
@@ -148,6 +148,13 @@ add_definitions(-DSTBI_FAILURE_USERMSG)
 # when gcc is used; otherwise saving PNGs may crash in stb_image_write
 if(SFML_COMPILER_GCC)
     set_source_files_properties(${SRCROOT}/ImageLoader.cpp PROPERTIES COMPILE_FLAGS -fno-strict-aliasing)
+
+endif()
+
+# see https://bugs.launchpad.net/ubuntu/+source/gcc-5/+bug/1568899
+if(SFML_COMPILER_GCC AND BUILD_SHARED_LIBS)
-    message(WARNING "Applying workaround for https://bugs.launchpad.net/ubuntu/+source/gcc-5/+bug/1568899")
-    list(APPEND GRAPHICS_EXT_LIBS "-lgcc_s -lgcc")
  endif()
  
  # define the sfml-graphics target
  
  ## 
  
  libgit2 0.24.0
